version: "3.8"
services:
  node:
    build:
      context: . # specify the Dir which Dockerfile is going to build
    volumes:
      - .:/app
    ports:
      - 3000:3000
    container_name: asobi-ct
    command: npm start # command when container spins up
